// ==========================================================================
// This is auto-generated by gf cli tool. Fill this file as you wish.
// ==========================================================================

package model

import (
	"github.com/lj1570693659/gfcq_product_kpi/app/model/internal"
)

// User is the golang structure for table user.
type User internal.User

// UserApiSignUpReq 注册请求参数，用于前后端交互参数格式约定
type UserApiSignUpReq struct {
	WorkNumber string `v:"required|length:6,16#账号不能为空|账号长度应当在:min到:max之间"`
	Password   string `v:"required|length:6,16#请输入确认密码|密码长度应当在:min到:max之间"`
	Password2  string `v:"required|length:6,16|same:Password#密码不能为空|密码长度应当在:min到:max之间|两次密码输入不相等"`
	UserName   string `v:"required#姓名不能为空"`
}

// UserApiSignInReq 登录请求参数，用于前后端交互参数格式约定
type UserApiSignInReq struct {
	WorkNumber string `v:"required#账号不能为空"`
	Password   string `v:"required#密码不能为空"`
}

// UserApiCheckWorkNumberReq 账号唯一性检测请求参数，用于前后端交互参数格式约定
type UserApiCheckWorkNumberReq struct {
	WorkNumber string `v:"required#账号不能为空"`
}

// UserApiCheckUserNameReq 昵称唯一性检测请求参数，用于前后端交互参数格式约定
type UserApiCheckUserNameReq struct {
	UserName string `v:"required#昵称不能为空"`
}

// UserServiceSignUpReq 注册输入参数
type UserServiceSignUpReq struct {
	WorkNumber string
	Password   string
	UserName   string
	CreateTime string
	UpdateTime string
}
