// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"context"
	"github.com/lj1570693659/gfcq_product_kpi/app/dao/internal"
	"github.com/lj1570693659/gfcq_product_kpi/app/model/entity"
)

// internalConfigDao is internal type for wrapping internal DAO implements.
type internalConfigDao = *internal.ConfigDao

// configDao is the data access object for table cqgf_config.
// You can define custom methods on it to extend its functionality as you wish.
type configDao struct {
	internalConfigDao
}

var (
	// Config is globally public accessible object for table cqgf_config operations.
	Config = configDao{
		internal.NewConfigDao(),
	}
)

// Fill with you ideas below.

func (s *configDao) GetOneByKeyName(ctx context.Context, keyName string) (res *entity.Config, err error) {
	res = &entity.Config{}
	err = s.Ctx(ctx).Where(s.Columns().KeyName, keyName).Scan(&res)
	return res, err
}

func (s *configDao) GetKeyValueByKeyName(ctx context.Context, keyName string) (value string, err error) {
	info, err := s.GetOneByKeyName(ctx, keyName)
	if err != nil {
		return "", err
	}
	return info.KeyValue, nil
}
