// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/lj1570693659/gfcq_product_kpi/app/dao/internal"
)

// internalCrewSolveRuleDao is internal type for wrapping internal DAO implements.
type internalCrewSolveRuleDao = *internal.CrewSolveRuleDao

// crewSolveRuleDao is the data access object for table cqgf_crew_solve_rule.
// You can define custom methods on it to extend its functionality as you wish.
type crewSolveRuleDao struct {
	internalCrewSolveRuleDao
}

var (
	// CrewSolveRule is globally public accessible object for table cqgf_crew_solve_rule operations.
	CrewSolveRule = crewSolveRuleDao{
		internal.NewCrewSolveRuleDao(),
	}
)

// Fill with you ideas below.
