// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"context"
	"github.com/lj1570693659/gfcq_product_kpi/app/dao/internal"
	"github.com/lj1570693659/gfcq_product_kpi/app/model"
)

// internalCrewKpiRuleDao is internal type for wrapping internal DAO implements.
type internalCrewKpiRuleDao = *internal.CrewKpiRuleDao

// crewKpiRuleDao is the data access object for table cqgf_crew_kpi_rule.
// You can define custom methods on it to extend its functionality as you wish.
type crewKpiRuleDao struct {
	internalCrewKpiRuleDao
}

var (
	// CrewKpiRule is globally public accessible object for table cqgf_crew_kpi_rule operations.
	CrewKpiRule = crewKpiRuleDao{
		internal.NewCrewKpiRuleDao(),
	}
)

// Fill with you ideas below.

func (s *crewKpiRuleDao) GetOne(ctx context.Context, in model.CrewKpiRule) (res *model.CrewKpiRule, err error) {
	productEntity := &model.CrewKpiRule{}
	query := s.Ctx(ctx)

	if len(in.LevelName) > 0 {
		query = query.Where(s.Columns().LevelName, in.LevelName)
	}
	if in.Id > 0 {
		query = query.Where(s.Columns().Id, in.Id)
	}

	if err = query.Scan(&productEntity); err != nil {
		return res, err
	}

	return productEntity, nil
}
