// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/lj1570693659/gfcq_product_kpi/app/dao/internal"
)

// internalCrewManageIndexDao is internal type for wrapping internal DAO implements.
type internalCrewManageIndexDao = *internal.CrewManageIndexDao

// crewManageIndexDao is the data access object for table cqgf_crew_manage_index.
// You can define custom methods on it to extend its functionality as you wish.
type crewManageIndexDao struct {
	internalCrewManageIndexDao
}

var (
	// CrewManageIndex is globally public accessible object for table cqgf_crew_manage_index operations.
	CrewManageIndex = crewManageIndexDao{
		internal.NewCrewManageIndexDao(),
	}
)

// Fill with you ideas below.
