// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/lj1570693659/gfcq_product_kpi/app/dao/internal"
)

// internalEmployeeJobDao is internal type for wrapping internal DAO implements.
type internalEmployeeJobDao = *internal.EmployeeJobDao

// employeeJobDao is the data access object for table cqgf_employee_job.
// You can define custom methods on it to extend its functionality as you wish.
type employeeJobDao struct {
	internalEmployeeJobDao
}

var (
	// EmployeeJob is globally public accessible object for table cqgf_employee_job operations.
	EmployeeJob = employeeJobDao{
		internal.NewEmployeeJobDao(),
	}
)

// Fill with you ideas below.
