// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/lj1570693659/gfcq_product_kpi/app/dao/internal"
)

// internalPmDutyIndexDao is internal type for wrapping internal DAO implements.
type internalPmDutyIndexDao = *internal.PmDutyIndexDao

// pmDutyIndexDao is the data access object for table cqgf_pm_duty_index.
// You can define custom methods on it to extend its functionality as you wish.
type pmDutyIndexDao struct {
	internalPmDutyIndexDao
}

var (
	// PmDutyIndex is globally public accessible object for table cqgf_pm_duty_index operations.
	PmDutyIndex = pmDutyIndexDao{
		internal.NewPmDutyIndexDao(),
	}
)

// Fill with you ideas below.
