// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/lj1570693659/gfcq_product_kpi/app/dao/internal"
)

// internalPmKpiRuleDao is internal type for wrapping internal DAO implements.
type internalPmKpiRuleDao = *internal.PmKpiRuleDao

// pmKpiRuleDao is the data access object for table cqgf_pm_kpi_rule.
// You can define custom methods on it to extend its functionality as you wish.
type pmKpiRuleDao struct {
	internalPmKpiRuleDao
}

var (
	// PmKpiRule is globally public accessible object for table cqgf_pm_kpi_rule operations.
	PmKpiRule = pmKpiRuleDao{
		internal.NewPmKpiRuleDao(),
	}
)

// Fill with you ideas below.
