// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/lj1570693659/gfcq_product_kpi/app/dao/internal"
)

// internalPmOvertimeRuleDao is internal type for wrapping internal DAO implements.
type internalPmOvertimeRuleDao = *internal.PmOvertimeRuleDao

// pmOvertimeRuleDao is the data access object for table cqgf_pm_overtime_rule.
// You can define custom methods on it to extend its functionality as you wish.
type pmOvertimeRuleDao struct {
	internalPmOvertimeRuleDao
}

var (
	// PmOvertimeRule is globally public accessible object for table cqgf_pm_overtime_rule operations.
	PmOvertimeRule = pmOvertimeRuleDao{
		internal.NewPmOvertimeRuleDao(),
	}
)

// Fill with you ideas below.
