// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/lj1570693659/gfcq_product_kpi/app/dao/internal"
)

// internalPmSolveRuleDao is internal type for wrapping internal DAO implements.
type internalPmSolveRuleDao = *internal.PmSolveRuleDao

// pmSolveRuleDao is the data access object for table cqgf_pm_solve_rule.
// You can define custom methods on it to extend its functionality as you wish.
type pmSolveRuleDao struct {
	internalPmSolveRuleDao
}

var (
	// PmSolveRule is globally public accessible object for table cqgf_pm_solve_rule operations.
	PmSolveRule = pmSolveRuleDao{
		internal.NewPmSolveRuleDao(),
	}
)

// Fill with you ideas below.
