// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/lj1570693659/gfcq_product_kpi/app/dao/internal"
)

// internalProductRolesDao is internal type for wrapping internal DAO implements.
type internalProductRolesDao = *internal.ProductRolesDao

// productRolesDao is the data access object for table cqgf_product_roles.
// You can define custom methods on it to extend its functionality as you wish.
type productRolesDao struct {
	internalProductRolesDao
}

var (
	// ProductRoles is globally public accessible object for table cqgf_product_roles operations.
	ProductRoles = productRolesDao{
		internal.NewProductRolesDao(),
	}
)

// Fill with you ideas below.
