// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/lj1570693659/gfcq_product_kpi/app/dao/internal"
)

// internalProductModeStageDao is internal type for wrapping internal DAO implements.
type internalProductModeStageDao = *internal.ProductModeStageDao

// productModeStageDao is the data access object for table cqgf_product_mode_stage.
// You can define custom methods on it to extend its functionality as you wish.
type productModeStageDao struct {
	internalProductModeStageDao
}

var (
	// ProductModeStage is globally public accessible object for table cqgf_product_mode_stage operations.
	ProductModeStage = productModeStageDao{
		internal.NewProductModeStageDao(),
	}
)

// Fill with you ideas below.
