// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"context"
	"encoding/json"
	"github.com/gogf/gf/util/gconv"
	"github.com/gogf/gf/v2/os/gtime"
	"github.com/lj1570693659/gfcq_product_kpi/app/dao/internal"
	"github.com/lj1570693659/gfcq_product_kpi/app/model"
	"github.com/lj1570693659/gfcq_product_kpi/app/model/do"
	"github.com/lj1570693659/gfcq_product_kpi/app/model/entity"
	"github.com/lj1570693659/gfcq_product_kpi/library/response"
	"github.com/lj1570693659/gfcq_product_kpi/library/util"
)

// internalProductMemberKpiDao is internal type for wrapping internal DAO implements.
type internalProductMemberKpiDao = *internal.ProductMemberKpiDao

// productMemberKpiDao is the data access object for table cqgf_product_member_kpi.
// You can define custom methods on it to extend its functionality as you wish.
type productMemberKpiDao struct {
	internalProductMemberKpiDao
}

var (
	// ProductMemberKpi is globally public accessible object for table cqgf_product_member_kpi operations.
	ProductMemberKpi = productMemberKpiDao{
		internal.NewProductMemberKpiDao(),
	}
)

// Fill with you ideas below.

func (s *productMemberKpiDao) GetAll(ctx context.Context, in model.ProductMemberKpi) (ent []*entity.ProductMemberKpi, err error) {
	ent = make([]*entity.ProductMemberKpi, 0)
	query := s.Ctx(ctx)
	// 项目名称
	if in.ProStageId > 0 {
		query = query.Where(s.Columns().ProStageId, in.ProStageId)
	}
	// 项目简称
	if in.ProId > 0 {
		query = query.Where(s.Columns().ProId, in.ProId)
	}
	// 项目经理投入程度
	if in.ProEmpId > 0 {
		query = query.Where(s.Columns().ProEmpId, in.ProEmpId)
	}
	if in.Id > 0 {
		query = query.Where(s.Columns().Id, in.Id)
	}

	if err = query.Scan(&ent); err != nil {
		return ent, err
	}
	return ent, nil
}

func (s *productMemberKpiDao) GetList(ctx context.Context, in model.ProductMemberKpi, page, size int32) (res *response.GetListResponse, err error) {
	res = &response.GetListResponse{}
	entity := make([]*entity.ProductMemberKpi, 0)
	query := s.Ctx(ctx)
	// 项目名称
	if in.ProStageId > 0 {
		query = query.Where(s.Columns().ProStageId, in.ProStageId)
	}
	// 项目简称
	if in.ProId > 0 {
		query = query.Where(s.Columns().ProId, in.ProId)
	}
	// 项目经理投入程度
	if in.ProEmpId > 0 {
		query = query.Where(s.Columns().ProEmpId, in.ProEmpId)
	}
	if in.Id > 0 {
		query = query.Where(s.Columns().Id, in.Id)
	}

	query, totalSize, page, size, err := util.GetListWithPage(query, page, size)
	if err != nil {
		return res, err
	}

	if err = query.Scan(&entity); err != nil {
		return res, err
	}

	res.Page = page
	res.Size = size
	res.TotalSize = totalSize
	res.Data = entity
	return res, nil
}

// Create 创建项目基础数据
func (s *productMemberKpiDao) Create(ctx context.Context, in *model.ProductMemberKpi) (*model.ProductMemberKpi, error) {
	data := do.ProductMemberKpi{}
	input, _ := json.Marshal(in)
	err := json.Unmarshal(input, &data)
	if err != nil {
		return in, err
	}

	data.CreateTime = gtime.Now()
	data.UpdateTime = gtime.Now()
	lastInsertId, err := s.Ctx(ctx).Data(data).InsertAndGetId()
	if err != nil {
		return in, err
	}

	in.Id = gconv.Uint(lastInsertId)
	return in, nil
}

func (s *productMemberKpiDao) GetOne(ctx context.Context, in model.ProductMemberKpi) (res *entity.ProductMemberKpi, err error) {
	res = &entity.ProductMemberKpi{}
	query := s.Ctx(ctx)
	// 项目名称
	if in.ProStageId > 0 {
		query = query.Where(s.Columns().ProStageId, in.ProStageId)
	}
	// 项目简称
	if in.ProId > 0 {
		query = query.Where(s.Columns().ProId, in.ProId)
	}
	// 项目经理投入程度
	if in.ProEmpId > 0 {
		query = query.Where(s.Columns().ProEmpId, in.ProEmpId)
	}
	if in.Id > 0 {
		query = query.Where(s.Columns().Id, in.Id)
	}

	err = query.Scan(&res)

	return res, err
}

// Modify 编辑项目基础数据
func (s *productMemberKpiDao) Modify(ctx context.Context, in *model.ProductMemberKpi) (*model.ProductMemberKpi, error) {
	data := do.ProductMemberKpi{}
	input, _ := json.Marshal(in)
	err := json.Unmarshal(input, &data)
	if err != nil {
		return in, err
	}

	data.UpdateTime = gtime.Now()
	_, err = s.Ctx(ctx).Where(s.Columns().Id, in.Id).Data(data).Update()
	if err != nil {
		return in, err
	}

	return in, nil
}
