// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/lj1570693659/gfcq_product_kpi/app/dao/internal"
)

// internalProductModeDao is internal type for wrapping internal DAO implements.
type internalProductModeDao = *internal.ProductModeDao

// productModeDao is the data access object for table cqgf_product_mode.
// You can define custom methods on it to extend its functionality as you wish.
type productModeDao struct {
	internalProductModeDao
}

var (
	// ProductMode is globally public accessible object for table cqgf_product_mode operations.
	ProductMode = productModeDao{
		internal.NewProductModeDao(),
	}
)

// Fill with you ideas below.
