// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/lj1570693659/gfcq_product_kpi/app/dao/internal"
)

// internalProductMemberKeyDao is internal type for wrapping internal DAO implements.
type internalProductMemberKeyDao = *internal.ProductMemberKeyDao

// productMemberKeyDao is the data access object for table cqgf_product_member_key.
// You can define custom methods on it to extend its functionality as you wish.
type productMemberKeyDao struct {
	internalProductMemberKeyDao
}

var (
	// ProductMemberKey is globally public accessible object for table cqgf_product_member_key operations.
	ProductMemberKey = productMemberKeyDao{
		internal.NewProductMemberKeyDao(),
	}
)

// Fill with you ideas below.
