// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/lj1570693659/gfcq_product_kpi/app/dao/internal"
)

// internalProductBudgetAccessDao is internal type for wrapping internal DAO implements.
type internalProductBudgetAccessDao = *internal.ProductBudgetAccessDao

// productBudgetAccessDao is the data access object for table cqgf_product_budget_access.
// You can define custom methods on it to extend its functionality as you wish.
type productBudgetAccessDao struct {
	internalProductBudgetAccessDao
}

var (
	// ProductBudgetAccess is globally public accessible object for table cqgf_product_budget_access operations.
	ProductBudgetAccess = productBudgetAccessDao{
		internal.NewProductBudgetAccessDao(),
	}
)

// Fill with you ideas below.
